name: Humanismo Secular Portugal
favicon: null
layout_spectrum: 0.5327067875768989
typography_spectrum: 0.06469151377677917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08285043621435761
  lightness: 0.7527317225467414
  saturation: 0.6825686998199672
  rhythmicContrast: 0.5584418480284512
purpose: []
